### PR TITLE
CB-11-YouTube-API

### PR DESCRIPTION
**Pull request by sunghyun96**
* **Please check if the PR fulfills these requirements**
- [x] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
Added post request to API which will return YouTube videos for recipes the user can watch.

* **What is the current behavior? What does the code do before you made the new changes?** 
There was no code using this API beforehand.

* **What is the new behavior?**
JSON data with an array of YouTube video URLs are returned when the post request is sent.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
There is no breaking change.

* **Other information**:

### CODE REVIEW

**Review by Stacey-Masi — APPROVED** [review]
Looks good, Sung!

**Review by AdemOdza — APPROVED** [review]
Looks good to me! I couldn't test it out myself but I think that's because the API wasn't running.

**Comment by saitanjavuru** [comment]
Everything looks good!

**Review by saitanjavuru — APPROVED** [review]
Everything looks good!

**Pull request merged**
